services:
  pgvector:
    image: 'pgvector/pgvector:pg16'
    environment:
      - 'POSTGRES_USER=user'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_DB=rag'
    labels:
      - "org.springframework.boot.service-connection=postgres"
    ports:
      - '5432:5432'
    volumes:
      - pgvector_data:/var/lib/postgresql/data

volumes:
  pgvector_data:

